/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package escola;

import javax.swing.JOptionPane;

/**
 *
 * @author Família
 */
public class Calc extends javax.swing.JFrame {
    
    String vetor[];
    String vetorNumeros[],operadores[];
    int i=0, i2=0;
    float valor=0;
    String valorfinal;
    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTexto = new javax.swing.JTextArea();
        butao3 = new javax.swing.JButton();
        butao2 = new javax.swing.JButton();
        butao4 = new javax.swing.JButton();
        butao5 = new javax.swing.JButton();
        butao1 = new javax.swing.JButton();
        butao6 = new javax.swing.JButton();
        butao8 = new javax.swing.JButton();
        butao9 = new javax.swing.JButton();
        butao7 = new javax.swing.JButton();
        butao0 = new javax.swing.JButton();
        butaoigual = new javax.swing.JButton();
        butaomais = new javax.swing.JButton();
        butaovezes = new javax.swing.JButton();
        butaomenos = new javax.swing.JButton();
        butaodividir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setName(""); // NOI18N

        AreaTexto.setColumns(20);
        AreaTexto.setRows(5);
        jScrollPane1.setViewportView(AreaTexto);

        butao3.setText("3");
        butao3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        butao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao3ActionPerformed(evt);
            }
        });

        butao2.setText("2");
        butao2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        butao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao2ActionPerformed(evt);
            }
        });

        butao4.setText("4");
        butao4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        butao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao4ActionPerformed(evt);
            }
        });

        butao5.setText("5");
        butao5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        butao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao5ActionPerformed(evt);
            }
        });

        butao1.setText("1");
        butao1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        butao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao1ActionPerformed(evt);
            }
        });

        butao6.setText("6");
        butao6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        butao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao6ActionPerformed(evt);
            }
        });

        butao8.setText("8");
        butao8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        butao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao8ActionPerformed(evt);
            }
        });

        butao9.setText("9");
        butao9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        butao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao9ActionPerformed(evt);
            }
        });

        butao7.setText("7");
        butao7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        butao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao7ActionPerformed(evt);
            }
        });

        butao0.setText("0");
        butao0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        butao0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao0ActionPerformed(evt);
            }
        });

        butaoigual.setText("=");
        butaoigual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        butaoigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoigualActionPerformed(evt);
            }
        });

        butaomais.setText("+");
        butaomais.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        butaomais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaomaisActionPerformed(evt);
            }
        });

        butaovezes.setText("x");
        butaovezes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        butaovezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaovezesActionPerformed(evt);
            }
        });

        butaomenos.setText("-");
        butaomenos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        butaomenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaomenosActionPerformed(evt);
            }
        });

        butaodividir.setText("/");
        butaodividir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        butaodividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaodividirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CALCULADORA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(butao1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(butao2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(butao3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(butao7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(butao8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(butao9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(butao4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(butao5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(butao6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(butao0, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(butaomenos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(butaodividir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(butaomais, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(butaoigual, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(butaovezes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butao3)
                    .addComponent(butao2)
                    .addComponent(butao1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butao4)
                    .addComponent(butao5)
                    .addComponent(butao6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butao8)
                    .addComponent(butao9)
                    .addComponent(butao7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butao0)
                    .addComponent(butaodividir)
                    .addComponent(butaomenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butaomais)
                    .addComponent(butaovezes)
                    .addComponent(butaoigual))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao2ActionPerformed
        // TODO add your handling code here:
        AreaTexto.setText(AreaTexto.getText()+"2") ;
        vetor[i]="2";
        i++;
    }//GEN-LAST:event_butao2ActionPerformed

    private void butao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao3ActionPerformed
        // TODO add your handling code here:
        AreaTexto.setText(AreaTexto.getText()+"3") ;
        vetor[i]="3";
        i++;
    }//GEN-LAST:event_butao3ActionPerformed

    private void butao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao1ActionPerformed
        // TODO add your handling code here:
         AreaTexto.setText(AreaTexto.getText()+"1") ;
         vetor[i]="1";
        i++;
         //aux = AreaTexto.getText() + AreaTexto.setText("1");;
    }//GEN-LAST:event_butao1ActionPerformed

    private void butao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao4ActionPerformed
        // TODO add your handling code here:
        AreaTexto.setText(AreaTexto.getText()+"4") ;
        vetor[i]="4";
        i++;
    }//GEN-LAST:event_butao4ActionPerformed

    private void butao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao5ActionPerformed
        // TODO add your handling code here:
        AreaTexto.setText(AreaTexto.getText()+"5") ;
        vetor[i]="5";
        i++;
    }//GEN-LAST:event_butao5ActionPerformed

    private void butao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao6ActionPerformed
        // TODO add your handling code here:
        AreaTexto.setText(AreaTexto.getText()+"6") ;
        vetor[i]="6";
        i++;
    }//GEN-LAST:event_butao6ActionPerformed

    private void butao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao7ActionPerformed
        // TODO add your handling code here:
        AreaTexto.setText(AreaTexto.getText()+"7") ;
        vetor[i]="7";
        i++;
    }//GEN-LAST:event_butao7ActionPerformed

    private void butao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao8ActionPerformed
        // TODO add your handling code here:
        AreaTexto.setText(AreaTexto.getText()+"8") ;
        vetor[i]="8";
        i++;
    }//GEN-LAST:event_butao8ActionPerformed

    private void butao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao9ActionPerformed
        // TODO add your handling code here:
        AreaTexto.setText(AreaTexto.getText()+"9") ;
        vetor[i]="9";
        i++;
    }//GEN-LAST:event_butao9ActionPerformed

    private void butao0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao0ActionPerformed
        // TODO add your handling code here:
        AreaTexto.setText(AreaTexto.getText()+"0") ;
        vetor[i]="0";
        i++;
    }//GEN-LAST:event_butao0ActionPerformed

    private void butaodividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaodividirActionPerformed
        // TODO add your handling code here:
            AreaTexto.setText(AreaTexto.getText()+"/") ;
            vetor[i]="/";
             i++;
       
    }//GEN-LAST:event_butaodividirActionPerformed

    private void butaomaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaomaisActionPerformed
        // TODO add your handling code here:
            AreaTexto.setText(AreaTexto.getText()+"+") ;
            vetor[i]="+";
            i++;
        
    }//GEN-LAST:event_butaomaisActionPerformed

    private void butaomenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaomenosActionPerformed
        // TODO add your handling code here:

            AreaTexto.setText(AreaTexto.getText()+"-") ;
            vetor[i]="-";
            i++;
        
    }//GEN-LAST:event_butaomenosActionPerformed

    private void butaovezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaovezesActionPerformed
        // TODO add your handling code here:
            AreaTexto.setText(AreaTexto.getText()+"x") ;
            vetor[i]="x";
            i++;
        
    }//GEN-LAST:event_butaovezesActionPerformed

    private void butaoigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoigualActionPerformed
        // TODO add your handling code here:
        for(int j=0;j<i;j++){
           if(vetor[j].equals("1") || vetor[j].equals("2") || vetor[j].equals("3") || vetor[j].equals("4") || vetor[j].equals("5") || vetor[j].equals("6") || vetor[j].equals("7") || vetor[j].equals("8") || vetor[j].equals("9") || vetor[j].equals("0")){
               vetorNumeros[i2] = vetorNumeros[i2]+ vetor[j];
          }
           if(vetor[j].equals("+") || vetor[j].equals("-") || vetor[j].equals("/") || vetor[j].equals("x")){
               operadores[i2] = vetor[j];
               i2++;
           }
        }
        for(int j=0;j<i;j++){
            if(operadores[j].equals("+")){
                float converter = Float.parseFloat(vetorNumeros[i2]) + Float.parseFloat(vetorNumeros[i2+1]);
                valor = valor + converter;
                valorfinal = String.valueOf(valor); 
               
            }
        }
         AreaTexto.setText(valorfinal);
        //String aux2= String.valueOf(valor);
        //JOptionPane.showMessageDialog(null,aux2);
        //AreaTexto.setText(aux2);
    }//GEN-LAST:event_butaoigualActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTexto;
    private javax.swing.JButton butao0;
    private javax.swing.JButton butao1;
    private javax.swing.JButton butao2;
    private javax.swing.JButton butao3;
    private javax.swing.JButton butao4;
    private javax.swing.JButton butao5;
    private javax.swing.JButton butao6;
    private javax.swing.JButton butao7;
    private javax.swing.JButton butao8;
    private javax.swing.JButton butao9;
    private javax.swing.JButton butaodividir;
    private javax.swing.JButton butaoigual;
    private javax.swing.JButton butaomais;
    private javax.swing.JButton butaomenos;
    private javax.swing.JButton butaovezes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
